### PR TITLE
Clean up

### LINKED ISSUE #226: `beavis-ci` failing on 2 tutorials, 1) GCR access -- HSC selection and 2) direct access -- color-color stellar locus
First noting the errors, then I will try to fix the notebooks (either by debugging or commenting out broken code). I'm not posting the links to the log files because they will get over-written when `beavis` runs again, but I'm getting all this by clicking on the red failing badges on the [README.rst page](https://github.com/LSSTDESC/DC2_Repo/blob/master/Notebooks/README.rst). 

### DC2 Coadd Run1.1p GCR access -- HSC selection.ipynb

Here's the extract from the log:
```
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
tract_number = 4850
mags = ['mag_g_lsst', 'mag_r_lsst', 'mag_i_lsst']
d = catalog.get_quantities(mags, 
                           filters=[GCRQuery((np.isfinite, key)) for key in mags] + ['mag_r_lsst < 25'], 
                           native_filters=[(lambda x: x==tract_number, 'tract')])
c = plt.scatter(d['mag_g_lsst'] - d['mag_r_lsst'], d['mag_r_lsst'] - d['mag_i_lsst'], s=2, c=d['mag_r_lsst']);
plt.colorbar(c, label='$r$')
plt.xlabel('$g-r$');
plt.ylabel('$r-i$');
------------------

ValueError: Native quantity `mag_r_lsst` does not exist (required by `mag_r_lsst`)
```

### DC2 Coadd Run1.1p direct access -- color-color stellar locus.ipynb

Here's the extract from the log:
```
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
# https://stackoverflow.com/questions/19390320/scatterplot-contours-in-matplotlib
def bin_kde(x, y, nbins=20, **kwargs):
    from scipy.stats import kde
    k = kde.gaussian_kde(x, y)
    xi, yi = np.mgrid[x.min():x.max():nbins*1j, y.min():y.max():nbis*1j]
    zi = k(np.vstack([xi.flatten(), yi.flatten()]))

# This doesn't exactly work, I've done something wrong here.
xi, yi, zi = bin_kde(stars['g_mag']-stars['r_mag'], stars['r_mag']-stars['i_mag'])
------------------

TypeError: invalid type comparison
```

### PR DESCRIPTION
**Pull request by yymao**
In this PR I 
- remove an outdated notebook
- remove the last cell of @wmwv's notebook so it can be rendered
- update readme

fix #226

### CODE REVIEW

**Comment by yymao** [comment]
@drphilmarshall is there a way to try out the new README with your building tool, or we have to merge this?

**Comment by drphilmarshall** [comment]
I'll give it a go.

**Comment by drphilmarshall** [comment]
OK, I added a `--branch` option to `beavis-ci` and tested the fixed stellar locus notebook, and it works - log below. I'll review the other bits too, next.

```
pjm43@cori19:/global/u2/p/pjm43/desc/DC2_Repo/Notebooks> ./beavis-ci.sh -n -b u/yymao/clean-upTue Jul 24 22:11:24 PDT 2018
Welcome to beavis-ci: occasional integration and testing
Cloning the DC2_Repo into the .beavis workspace:
Cloning into 'DC2_Repo'...
remote: Counting objects: 1866, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 1866 (delta 43), reused 64 (delta 29), pack-reused 1782
Receiving objects: 100% (1866/1866), 10.93 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1109/1109), done.
Branch u/yymao/clean-up set up to track remote branch u/yymao/clean-up from origin.
Switched to a new branch 'u/yymao/clean-up'
Rendering the master branch notebooks:
DC2_Coadd_Run1.1p_direct_access_--_color-color_stellar_locus.ipynb
Running nbconvert on DC2_Coadd_Run1.1p_direct_access_--_color-color_stellar_locus.ipynb ...
SUCCESS: DC2_Coadd_Run1.1p_direct_access_--_color-color_stellar_locus.nbconvert.ipynb produced.
beavis-ci finished: view the results at
   https://github.com/LSSTDESC/DC2_Repo/tree/u/yymao/clean-up/Notebooks
Tue Jul 24 22:11:46 PDT 2018
```

**Comment by drphilmarshall** [comment]
And, just for completeness, here's the full `beavis` report, and [the lights are all green](https://github.com/LSSTDESC/DC2_Repo/blob/master/Notebooks/README.rst) :-)

```
Running nbconvert on DC2_Coadd_Run1.1p_GCR_tutorial_--_Part_I:_GCR_Access.ipynb ...
SUCCESS: DC2_Coadd_Run1.1p_GCR_tutorial_--_Part_I:_GCR_Access.nbconvert.ipynb produced.
Running nbconvert on DC2_Coadd_Run1.1p_GCR_tutorial_--_Part_II:_Lensing_Cuts.ipynb ...
SUCCESS: DC2_Coadd_Run1.1p_GCR_tutorial_--_Part_II:_Lensing_Cuts.nbconvert.ipynb produced.
Running nbconvert on DC2_Coadd_Run1.1p_GCR_tutorial_--_Part_III:_Guided_Challenges.ipynb ...
SUCCESS: DC2_Coadd_Run1.1p_GCR_tutorial_--_Part_III:_Guided_Challenges.nbconvert.ipynb produced.
Running nbconvert on DC2_Coadd_Run1.1p_direct_access_--_color-color_stellar_locus.ipynb ...
SUCCESS: DC2_Coadd_Run1.1p_direct_access_--_color-color_stellar_locus.nbconvert.ipynb produced.
Running nbconvert on DC2_Coadd_Run1.1p_Butler_Access_HSC_selection.ipynb ...
SUCCESS: DC2_Coadd_Run1.1p_Butler_Access_HSC_selection.nbconvert.ipynb produced.
Running nbconvert on DC2_Postage_Stamps.ipynb ...
SUCCESS: DC2_Postage_Stamps.nbconvert.ipynb produced.
Running nbconvert on Plotting_the_Run1.1p_skymap.ipynb ...
SUCCESS: Plotting_the_Run1.1p_skymap.nbconvert.ipynb produced.
Running nbconvert on LSST_Stack_matching_code.ipynb ...
SUCCESS: LSST_Stack_matching_code.nbconvert.ipynb produced.
Running nbconvert on FoFCatalogMatching_Histogram.ipynb ...
SUCCESS: FoFCatalogMatching_Histogram.nbconvert.ipynb produced.
Running nbconvert on DC2_truth_example.ipynb ...
SUCCESS: DC2_truth_example.nbconvert.ipynb produced.
Running nbconvert on N_vs_z_distributions.ipynb ...
SUCCESS: N_vs_z_distributions.nbconvert.ipynb produced.
Running nbconvert on protoDC2_HOD.ipynb ...
SUCCESS: protoDC2_HOD.nbconvert.ipynb produced.
Running nbconvert on protoDC2_mass_relations.ipynb ...
SUCCESS: protoDC2_mass_relations.nbconvert.ipynb produced.
Running nbconvert on ProtoDC2_Cluster_Colors.ipynb ...
SUCCESS: ProtoDC2_Cluster_Colors.nbconvert.ipynb produced.
Running nbconvert on ProtoDC2_Cluster_Member_Cutout.ipynb ...
SUCCESS: ProtoDC2_Cluster_Member_Cutout.nbconvert.ipynb produced.
```

**Comment by yymao** [comment]
:tada: thanks, @drphilmarshall

**Pull request merged**
