### PR TITLE
initial list of prod software configuration

### PR DESCRIPTION
**Pull request by jchiang87**

### CODE REVIEW

**Comment by yymao** [comment]
@jchiang87 is there a deadline for sending your the tagged versions for Run 1.1p?

**Comment by jchiang87** [comment]
Given the other on-going development, I think Monday Jan 29 is a reasonable deadline (assuming we are working over the weekend.)  If you can make a tag sooner, that would be fine of course.

**Comment by jbkalmbach** [comment]
Updated the Twinkles package due to error found in the dec values for the lensed images. Validation now shows the images in the correct locations.

**Comment by jchiang87** [comment]
@heather999 Twinkles DC2-Run1.1-v4 needs to be installed in the prod area at NERSC. @TomGlanzman This is a heads-up about this update.

**Comment by jchiang87** [comment]
I've installed Twinkles DC2-Run1.1-v4 and sims_GCRCatSimInterface v0.1.1 (see [this PR](https://github.com/LSSTDESC/sims_GCRCatSimInterface/pull/26)) in the prod area at NERSC and updated the setup file `/global/common/software/lsst/cori-haswell-gcc/Run1.1p_setup.bash` to use the new versions.

**Comment by jchiang87** [comment]
@heather999 I've changed the required package to support the DRP pipeline from `lsst_apps` to `lsst_distrib`.  For the sims work, including the Run1.1p image generation, `lsst_apps` is sufficient, but we'll need `lsst_distrib` in the shifter image, assuming that's what we'll use in the DRP pipeline.  It would also be good to have that in `/global/common/software/lsst/cori-haswell-gcc/stack`.

**Comment by heather999** [comment]
I just double-checked the lsstdesc/stack-sims:w_2018_03-sims_2_5_0 and it already has lsst_distrib and lsst_apps.  Which makes sense, since that docker image is based on the lsstsqre image. Now that Scott has updated the sims tag to include lsst_distrib, just for clean living, I'm going to remake that docker image and then upload it into shifter at NERSC.  I'll look at updating cori-haswell-gcc/stack now.

**Comment by TomGlanzman** [comment]
A question about what I should expect to appear in the 'prod' area...the phosim workflow has dependencies on sims_GCRCatSimInterface, but also DC2_Repo and gcr-catalogs.  Will/Should these other packages also appear within 'prod'?

**Comment by jchiang87** [comment]
gcr-catalogs is installed as part of the Stack installation and so does not appear as a separate entity in the prod area.  DC2_Repo does need to be put there, but there are outstanding pull-requests that need to be resolved.  For your testing, we can install DC2_Repo in the prod area as a git repo with the intention of replacing that installation with the final tagged version.  Will that work for you @TomGlanzman ?

**Comment by TomGlanzman** [comment]
Yes, thanks.  As a sanity check, this is what I think should happen.  The *current* setup relies on local clones of the DC2_Repo, gcr-catalogs and sims_GCRCatSimInterface with this setup,  

```
source /global/common/software/lsst/cori-haswell-gcc/stack/setup_w_2017_46_py3_gcc6.sh
setup lsst_sims
eups declare gcr_catalogs -r ${PHOSIM_IC_GCR_CATALOGS}  -c
setup gcr_catalogs
source $PHOSIM_IC_GCRCATSIM/setup/setup.sh
```
where PHOSIM_IC_GCR_CATALOGS and PHOSIM_IC_GCRCATSIM point to my local clones.  It appears I may replace all of that with Run1.1p_setup.bash which contains:

```
common_software=/global/common/software/lsst/cori-haswell-gcc
install_date_folder=20180203
source ${common_software}/stack/setup_w_2018_03_py3.sh
setup lsst_sims
setup -r ${common_software}/twinkles/Twinkles-DC2-Run1.1-v4 -j
setup -r ${common_software}/sims_GCRCatSimInterface/sims_GCRCatSimInterface-0.1.1 -j
export PYTHONPATH=${common_software}/OM10/${install_date_folder}:${common_software}/LensPop/${install_date_folder}:${PYTHONPATH}
```
Once setup, I can reference generateInstCat.py without specifying an explicit path.
---

For DC2_Repo, I reference the needed datafiles (visit lists, and phosim command file) directly from my local clone, so that is trivial to change.  @jchiang87, are the needed changes to DC2_Repo relevant to those data files?  Or are there new dependencies on this repo?

**Comment by jchiang87** [comment]
The only pending changes in DC2_Repo that need to be approved are the visit lists.  There should be no new dependencies.

**Comment by jchiang87** [comment]
@TomGlanzman @katrinheitmann This is the final pull-request that needs to be merged before we start phosim image production.  I would like to merge this and make a release tag of DC2_Repo to capture all of the production-level configuration for Run1.1p image production.   For image processing, we can make a new PR and fill in the blanks for the relevant packages.

So the last two bits for image production are a tag of DC2-phosim-2 and then the final tag on this repo itself.  @TomGlanzman Just prior to your sign off on this PR, can you add the release version of DC2-phosim-2 that you intend to use?   @katrinheitmann I'd like your final approval before I make the release tag of this repo.  Thanks!

**Comment by katrinheitmann** [comment]
Just to be clear, I'll have to wait then until Tom has added his release 
version number, right? Thanks very much!

**Comment by jchiang87** [comment]
Yes, please.  I'd like at least another pair of eyes to make sure everything looks ok.

**Comment by TomGlanzman** [comment]
I will not know the release tag for DC2-phoSim-3 until I test it with all production tags/links/etc.

**Comment by jchiang87** [comment]
Everything is in place except DC2_Repo (this repo).  We can put it in exactly the place where you would use it for production.  Is that what you would need to make that tag?

**Comment by TomGlanzman** [comment]
Yes, I think that would do it.

**Comment by cwwalter** [comment]
> looked through it. It all looks good. What I noticed is that for lsst_distrib there is a newer version than what we list (06 instead of 03)

I think we need to use that one since sims 2.5.0 was built against the _3 weekly lsst_distrib tag.

**Comment by danielsf** [comment]
Chris is correct: sims_2_5_0 is built assuming w_2018_03

**Comment by jchiang87** [comment]
@TomGlanzman In your `generateInstCat.py` example, the `fov` option should be `--fov 2.1` in order to cover the entire focalplane.  I think a `2.1` degree radius field-of-view may be a little conservative.  @sethdigel Do you know the right number?

**Comment by TomGlanzman** [comment]
The first test of the phosim workflow using the latest instance catalog generation, including the dynamic SEDs is complete: a single visit, 181865, r-band in the WFD survey.  Output data products (electron, amplifier and centroid files) are here:
/global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-3_WFD-r/output/000001

Note: the "--fov 0.5" parameter setting was used for this test.

**Comment by TomGlanzman** [comment]
I am satisfied that the code @jchiang87 and others have prepared is usable and allows the phosim workflow to function successfully to completion.  

The instanceCatalog generation "--fov" issue is for the workflow scripts, so can be ignored here.  (Who will comment on this issue?  @sethdigel ?)

**Comment by jchiang87** [comment]
I just asked Seth, but he doesn't recall a precise number.  I can dig it up or use the catsim code to compute it.  I will post here once I have it.

**Comment by jchiang87** [comment]
@TomGlanzman Using the sims code, I find the maximum corner pixel distance for all of the science sensors in the simulated LSST focalplane from the nominal pointing direction to be 2.047 degrees, so `--fov=2.1` is a good setting to use for `generateInstCat.py`.

**Pull request merged**
