### PR TITLE
Fixes the number of patches for HSC

### PR DESCRIPTION
**Pull request by EiffL**
@wmwv @yymao This is a very small PR that sets the number of patches for HSC. Unfortunately, the Butler doesn't let you query the number of patches, so you would have to dig into the repository tree to figure it out programmatically (and it quickly gets ugly when you have to handle different filter names).

We will have to regenerate the HDF5 for hsc with this new version of the script.

### CODE REVIEW

**Comment by jchiang87** [comment]
@EiffL You can also just iterate via `for patch in tract` and use a try/except block and catch the `NoResults` exception to avoid assuming a specific number of patches per tract:
https://github.com/LSSTDESC/DC2_Repo/blob/u/jchiang/cmu_tutorials/Notebooks/DC2_Coadd_Run1.1p_Butler_Access_HSC_selection.ipynb

**Comment by wmwv** [comment]
Or if you want to be explicit, you can
```
skymap = butler.get(datasetType='deepCoadd_skyMap')
tractId = 4850
tract = skymap.generateTract(tractId)
numpatches = tId.getNumPatches()
nx, ny = numpatches.getX(), numpatches.getY()
patches = ['%d,%d' % (i, j) for i in range(nx)
                            for j in range(ny)]
```

**Comment by wmwv** [comment]
But I really like @jchiang87 's suggestion.  Replace the logic in `load_tract`:

**Comment by EiffL** [comment]
ok great :-) I like this a lot! Replacing it now

**Comment by EiffL** [comment]
Looks good, and it's running, I'm reprocessing tract 8523, will take a number of hours

**Comment by yymao** [comment]
@EiffL The code should work but I thought the idea is to remove Lines 86 to 91 and change Line 93 to `for patch in tract:`?

**Comment by EiffL** [comment]
Yes, my bad. Here, it's fixed :-) And no, I don't think we want to directly use `for patch in tract` at the next line, because we might want to specify a subset of patches

**Comment by yymao** [comment]
Should edit `load_tract` accordingly too.

**Comment by EiffL** [comment]
facepalm, thanks Yao! I think I should take a break from touching critical code for today.

**Comment by EiffL** [comment]
Ok, everything seems to work.

**Pull request merged**
