### PR TITLE
tutorial notebooks for extragalactic catalogs

### PR DESCRIPTION
**Pull request by yymao**
Open a PR so it is easier to find. This PR addresses #183.

Right now there are
- [mass relations](https://github.com/LSSTDESC/DC2_Repo/blob/u/yymao/cmu_tutorials/Notebooks/protoDC2%20mass%20relations.ipynb)
- [HOD](https://github.com/LSSTDESC/DC2_Repo/blob/u/yymao/cmu_tutorials/Notebooks/protoDC2%20HOD.ipynb)

To-do:
- [x] add learning objectives

### CODE REVIEW

**Comment by yymao** [comment]
Both notebooks are now ready to review.

**Comment by yymao** [comment]
Thanks, @evevkovacs. I think you need to choose "approve" in your review if you are approving :)

**Comment by evevkovacs** [comment]
Sorry, I thought I did. Should be approved now.

**Comment by yymao** [comment]
Thanks again, @evevkovacs.

Now, can I just merge this or do I need to do something with the CIT system? @drphilmarshall

**Comment by wmwv** [comment]
Merge it.

The CIT system processes the notebooks on `master`.

**Pull request merged**
